line-length = 110
target-version = "py311"
extend-exclude = ["pilot/_vendor"]

[format]
indent-style = "space"
line-ending = "auto"
quote-style = "double"

[lint]
select = [
  "F",
  "E",
  "W",
  "I",
  "UP",
  "B",
  "RUF",
  "FA",
  "TCH",
  "C90",
  "RET",
  "SIM",
]
ignore = [
  "UP015",
  "SIM108",
  "F821",
  "F722",
  "E501",
  "W191",
  "B023",
  "TCH001",
  "TCH002",
  "TCH003",
  "UP037",
  "SIM103",
]

[lint.mccabe]
max-complexity = 8

[lint.per-file-ignores]
"**/test_*.py" = ["C901"]
"tests/e2e/**" = ["C901"]
